version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    container_name: kg_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - kg_network

  redis:
    image: redis:7-alpine
    container_name: kg_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kg_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:

networks:
  kg_network:
    driver: bridge
